spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: oracle123
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: project
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

      

server:  port: 1213   
      